### ISSUE TITLE
Port forwarding fails randomly

### ISSUE THREAD

**Issue by summerwind** [winebarrel/demitas2#2]
Hi, Thank you for developing the useful command!

Let me just report a problem.
I have encountered command termination randomly when using port forwarding.

I believe that when `dmts` tries to access via Session Manager right after the ECS Task is launched, it fails because Session Manager does not recognize the ECS Task yet. I tried to fix this problem to wait 5 seconds after starting the container before connecting around the following code, and the problem went away.
https://github.com/winebarrel/demitas2/blob/a7b99d6d435364e6caa612537f80096526c9aedc/subcmd/port_forward.go#L55

**Comment by winebarrel** [comment]
Thank you for your report 😃 
I will fix it at https://github.com/winebarrel/demitas2/pull/3

**Comment by summerwind** [comment]
Thanks for your quick response!
